# Generated by Django 4.2 on 2023-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDeliveryTechnovizor', '0002_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
