# Generated by Django 4.2 on 2023-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDeliveryTechnovizor', '0003_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(to='FoodDeliveryTechnovizor.dish'),
        ),
    ]
