# Generated by Django 4.2 on 2023-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDeliveryTechnovizor', '0004_remove_order_dish_order_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(related_name='orders', to='FoodDeliveryTechnovizor.dish'),
        ),
    ]
