# Generated by Django 4.2 on 2023-05-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDeliveryTechnovizor', '0005_alter_order_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
