# Generated by Django 4.2 on 2023-05-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDeliveryTechnovizor', '0006_alter_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
